dist: focal
language: bash
virt: edge 

addons:
  apt:
    packages: ['moreutils']

branches:
  only:
    - master
    - /^(cherry-pick-)?backport-\d+-to-/
    
script:
  - chmod u+x fetch_terraform.sh
